name: bloc_deep_dive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc_concurrency: ^0.3.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  formz: ^0.8.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.2.4
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  json_annotation: ^4.9.0
  logger: ^2.6.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
